


/* Drop Tables */

DROP TABLE IF EXISTS INVITADO_ACOMPANANTE;
DROP TABLE IF EXISTS ACOMPANATE;
DROP TABLE IF EXISTS CORREO_INVITADOS;
DROP TABLE IF EXISTS CORREO_INVITACION;
DROP TABLE IF EXISTS INVITADOS_MATRIMONIO;
DROP TABLE IF EXISTS INVITADOS;
DROP TABLE IF EXISTS MATRIMONIO_REGALO;
DROP TABLE IF EXISTS USUARIO_MATRIMONIO;
DROP TABLE IF EXISTS MATRIMONIO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS PERFIL;
DROP TABLE IF EXISTS REGALOS;




/* Create Tables */

CREATE TABLE ACOMPANATE
(
	IDACOMPANANTE BIGSERIAL NOT NULL,
	NOMBRE_ACOMPANANTE VARCHAR(250),
	PRIMARY KEY (IDACOMPANANTE)
) WITHOUT OIDS;


CREATE TABLE CORREO_INVITACION
(
	IDCORREO_INVITACION BIGSERIAL NOT NULL,
	-- 0: NO ENVIAR
	-- 1: ENVIAR
	-- 2: ENVIAR EN FECHA X
	ESTADO_CORREOINVITACION INT DEFAULT 0,
	FECHA_CORREO_INVITACION DATE,
	PRIMARY KEY (IDCORREO_INVITACION)
) WITHOUT OIDS;


CREATE TABLE CORREO_INVITADOS
(
	IDCORREO_INVITADOS BIGSERIAL NOT NULL,
	IDCORREO_INVITACION BIGINT NOT NULL,
	IDINVITADOS BIGINT NOT NULL,
	PRIMARY KEY (IDCORREO_INVITADOS)
) WITHOUT OIDS;


CREATE TABLE INVITADOS
(
	IDINVITADOS BIGSERIAL NOT NULL,
	NOMBRE_INVITADO VARCHAR(250),
	CORREO_INVITADO VARCHAR(250),
	PRIMARY KEY (IDINVITADOS)
) WITHOUT OIDS;


CREATE TABLE INVITADOS_MATRIMONIO
(
	IDINVITADOS_MATRIMONIO BIGSERIAL NOT NULL,
	IDINVITADOS BIGINT NOT NULL,
	IDMATRIMONIO BIGINT NOT NULL,
	PRIMARY KEY (IDINVITADOS_MATRIMONIO)
) WITHOUT OIDS;


CREATE TABLE INVITADO_ACOMPANANTE
(
	IDINVITADO_ACOMPANANTE BIGSERIAL NOT NULL,
	IDINVITADOS BIGINT NOT NULL,
	IDACOMPANANTE BIGINT NOT NULL,
	PRIMARY KEY (IDINVITADO_ACOMPANANTE)
) WITHOUT OIDS;


CREATE TABLE MATRIMONIO
(
	IDMATRIMONIO BIGSERIAL NOT NULL,
	FECHA_MATRIMONIO DATE NOT NULL,
	LUGAR_MATRIMONIO VARCHAR(500),
	PRIMARY KEY (IDMATRIMONIO)
) WITHOUT OIDS;


CREATE TABLE MATRIMONIO_REGALO
(
	IDMATRIMONIO_REGALO BIGSERIAL NOT NULL,
	IDREGALOS BIGINT NOT NULL,
	IDMATRIMONIO BIGINT NOT NULL,
	PRIMARY KEY (IDMATRIMONIO_REGALO)
) WITHOUT OIDS;


CREATE TABLE PERFIL
(
	IDPERFIL BIGSERIAL NOT NULL,
	NOMBRE_PERFIL VARCHAR(250),
	PRIMARY KEY (IDPERFIL)
) WITHOUT OIDS;


CREATE TABLE REGALOS
(
	IDREGALOS BIGSERIAL NOT NULL,
	NOMBRE_REGALO VARCHAR(250),
	VALOR_REGALO BIGINT,
	PRIMARY KEY (IDREGALOS)
) WITHOUT OIDS;


CREATE TABLE USUARIO
(
	IDUSUARIO BIGSERIAL NOT NULL,
	NOMBRE_USUARIO VARCHAR(250) NOT NULL,
	CORREO_USUARIO VARCHAR(250),
	CLAVE_USUARIO VARCHAR(250),
	IDPERFIL BIGINT NOT NULL,
	PRIMARY KEY (IDUSUARIO)
) WITHOUT OIDS;


CREATE TABLE USUARIO_MATRIMONIO
(
	IDUSUARIO_MATRIMONIO BIGSERIAL NOT NULL,
	IDUSUARIO BIGINT NOT NULL,
	IDMATRIMONIO BIGINT NOT NULL,
	PRIMARY KEY (IDUSUARIO_MATRIMONIO)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE INVITADO_ACOMPANANTE
	ADD FOREIGN KEY (IDACOMPANANTE)
	REFERENCES ACOMPANATE (IDACOMPANANTE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CORREO_INVITADOS
	ADD FOREIGN KEY (IDCORREO_INVITACION)
	REFERENCES CORREO_INVITACION (IDCORREO_INVITACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CORREO_INVITADOS
	ADD FOREIGN KEY (IDINVITADOS)
	REFERENCES INVITADOS (IDINVITADOS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INVITADOS_MATRIMONIO
	ADD FOREIGN KEY (IDINVITADOS)
	REFERENCES INVITADOS (IDINVITADOS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INVITADO_ACOMPANANTE
	ADD FOREIGN KEY (IDINVITADOS)
	REFERENCES INVITADOS (IDINVITADOS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE INVITADOS_MATRIMONIO
	ADD FOREIGN KEY (IDMATRIMONIO)
	REFERENCES MATRIMONIO (IDMATRIMONIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATRIMONIO_REGALO
	ADD FOREIGN KEY (IDMATRIMONIO)
	REFERENCES MATRIMONIO (IDMATRIMONIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_MATRIMONIO
	ADD FOREIGN KEY (IDMATRIMONIO)
	REFERENCES MATRIMONIO (IDMATRIMONIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO
	ADD FOREIGN KEY (IDPERFIL)
	REFERENCES PERFIL (IDPERFIL)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE MATRIMONIO_REGALO
	ADD FOREIGN KEY (IDREGALOS)
	REFERENCES REGALOS (IDREGALOS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE USUARIO_MATRIMONIO
	ADD FOREIGN KEY (IDUSUARIO)
	REFERENCES USUARIO (IDUSUARIO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN CORREO_INVITACION.ESTADO_CORREOINVITACION IS '0: NO ENVIAR
1: ENVIAR
2: ENVIAR EN FECHA X';



